import Head from "@app/layout/Head/Head";

export default function Home() {
  return (
    <>
      <Head
        title="Create Next App"
        description="Generated by create next app"
      />
      <main>
        <h1>Hello World</h1>
      </main>
    </>
  );
}
