import Head from "@app/components/Head/Head";

export default function Home() {
  return (
    <>
      <Head
        title="Create Next App"
        description="Generated by create next app"
      />
      <main></main>
    </>
  );
}
